require "sudonick.options"
require "sudonick.keymaps"
require "sudonick.plugins"
require "sudonick.colors"
require "sudonick.cmp"
require "sudonick.lsp"
require "sudonick.telescope"
require "sudonick.treesitter"
require "sudonick.autopairs"
require "sudonick.comment"
require "sudonick.gitsigns"
-- require "sudonick.nvim-tree"
-- require "sudonick.bufferline"
require "sudonick.lualine"
-- require "sudonick.toggleterm"
-- require "sudonick.project"
require "sudonick.netrw"
require "sudonick.impatient"
-- require "sudonick.indentline"
require "sudonick.alpha"
require "sudonick.whichkey"
require "sudonick.autocommands"
require "sudonick.gruvbox"
require "sudonick.global"
require "sudonick.harpoon"
